# Generated by Django 2.1.3 on 2018-12-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('lastName', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=300)),
            ],
        ),
    ]
